### ISSUE TITLE
Can some one explain what is happening in example 6.

### ISSUE THREAD

**Issue by rohitrameshrao** [jarvelov/vue-form-json-schema#25]
Example link: https://4rykx7jj19.codesandbox.io/

Few questions: 

- How is the submit button coming up?
- The UI schema has so many params. How do I know what is doing what. Eg:  errorHandler, displayOptions etc.
- Why is "not" defined as string for first name. Moreover, schema->properties already knows that first name is a string.

I really like the concept of generating forms using JSON but I just can't get my head around how to use this.

**Comment by jarvelov** [comment]
First and foremost it seems like you need to familiarize yourself with JSON schema and how it works.  Refer to this guide if you haven't already: https://json-schema.org/understanding-json-schema/

Simply put it is a set of rules for how a schema can be constructed with JSON, and we use those schemas not only for validating form fields but to be able to hide/show fields depending on if a schema validates to true or not. More on this later.

If you go to the source for this example you can get a better idea of how it works: https://codesandbox.io/s/4rykx7jj19

The submit button is just markup in the `components/example-six.vue` file

```html
      <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit form</button>
      </div>
```
All the features are documented on gitbook: https://jarvelov.gitbook.io/vue-form-json-schema/

Here's the documentation for `displayOptions` for example: https://jarvelov.gitbook.io/vue-form-json-schema/api/vue-form-json-schema/ui-schema/field/display-options

About the `"not"`

```js
              displayOptions: {
                model: "firstName",
                schema: {
                  not: {
                    type: "string"
                  }
                }
              }
```

Why the "not" is used is because displayOptions is a way to hide or show a field depending on if a JSON schema passes its validation. Here we have two properties: `model` and `schema`. The `model` lets us target a specific key in the form's `model`, i.e. the object which stores all the form values. We then get the value for that key from the form's model and test if it passes the schema in the `schema` key.

You can try this out yourself:
https://www.jsonschemavalidator.net/

Paste this in the left box and write something that isn't a string (i.e. "any value within quotes" such as numbers, arrays or objects). 
```
{
  not: {
    type: "string"
  }
}
```

The "not" itself is just what JSON schema uses to invert logic. If you just use `{ type: "string" }` as a schema it will only pass validation for values that are strings. With this example we instruct the field to hide itself if the schema fails its validation, or show itself it the validation passes.

With good knowledge of JSON schema we can construct a schema for any type of situation, and this schema is constructed to be applicable to situations where a user has entered something into the input and then cleared the input (removed all characters). This removes the key from the form model and thus the JSON schema will fail because it will evaluate an `undefined` value. When the schema in a `displayOptions` fails `vue-form-json-schema` will not show the field and it will remain hidden until the schema in `displayOptions` passes again.

I hope this clears some things up, if you still have any questions I'll try to answer them to the best of my abilities.

**Comment by rohitrameshrao** [comment]
Thanks so much for the information and taking time out to write in this detail. I am assuming the biggest gap for me was JSON SCHEMA. Will go through that and try using this again.
