### ISSUE TITLE
Conditional Classes

### ISSUE THREAD

**Issue by broomhandleus** [jarvelov/vue-form-json-schema#44]
I see from the examples how you can apply custom classes to each element within vfjs, but how do I go about making these classes conditional? I can bind classes to certain variables so that they're only activated in certain situations with vue - [https://vuejs.org/v2/guide/class-and-style.html](url) - but i didn't see how to do that in the examples given. Apologies if I missed it. Thanks!

**Comment by jarvelov** [comment]
Hi!

There are a couple of different ways you can achieve this. Either by constructing the `uiSchema` as a computed property, which is then updated when the conditions are changed. Or you might be able to achieve this using [`errorOptions`](https://jarvelov.gitbook.io/vue-form-json-schema/api/vue-form-json-schema/ui-schema/field/error-options) and/or [`displayOptions`](https://jarvelov.gitbook.io/vue-form-json-schema/api/vue-form-json-schema/ui-schema/field/display-options).

Here is an example of the first option by using `uiSchema` as a computed property: https://codesandbox.io/s/issue-44-riptz

Basically instead of declaring your `uiSchema` in the `data` property you place it as a `computed` property, which will then be re-run when any variables used in the function are changed. The essential bits are shown below:

Instead of:

```js
data() {
  return {
    uiSchema: [{
      component: "div",
      fieldOptions: {
        class: ["default"] // No way to set another className here
      }
    }]
  }
}
```

You would do:

```js
computed: {
  uiSchema: {
    const classNames = [this.model.primary ? "primary" : "default"]
    return [{
      component: "div",
      fieldOptions: {
        class: classNames
      }
    }]
  }
}
```

---

`errorOptions`/`displayOptions` provide a way to handle conditions without using JavaScript, however there are many limitations to using them. If you are interested check out the links above to the documentation or write another comment and I'll try to help you get sorted.

**Comment by broomhandleus** [comment]
I'll definitely give this a shot when I'm back at work next week. Thank you! I've been writing the UI Schemas in separate files, then importing them so that I don't have this giant JSON object in my script area, but it seems like I'll need to have it in the computed properties if I want this type of reactivity. when I try it out I'll let you know how it works! Thank you again!

**Comment by jarvelov** [comment]
Just figured I should let you know, even though Vue promotes the Single File Component, you can still split up things into different files. You still get reactivity. So you can just as easy do this:

```js
// uiSchema.js
export default function uiSchema() {
  return [{
    component: 'div',
    ... // Rest of UI schema
  }];
}
```

```js
// component.js
import uiSchema from './uiSchema.js';

...
{
  computed: {
    uiSchema
  }
}
...
```

**Comment by broomhandleus** [comment]
Ok that's perfect. I had just assumed since you threw the schema into the computed property that it had to be there, but I suppose you were just following Vue best practice! I was just worried about how long the file will get because these schemas get pretty beefy fairly quickly. Thanks for steering me the right way!

**Comment by jarvelov** [comment]
Since many people use issues to look for help or tips I figured I should mention in this issue that in `v2.6.0` the [dynamicOptions](https://jarvelov.gitbook.io/vue-form-json-schema/api/vue-form-json-schema/ui-schema/field/dynamic-options) feature was released. The `dynamicOptions` feature allows you to conditionally apply field properties depending on the model.

Instead of applying classes conditionally using JavaScript you can now include them in your UI Schema using only JSON.

If we take the example I provided above:

```js
uiSchema: [{
  component: 'button'
  fieldOptions: {
    class: [this.model.primary ? 'btn-primary' : 'btn-default']
  }
}]
```

And if we were to rewrite this to use `dynamicOptions` we can just do the following:

```js
uiSchema: [{
  component: 'button',
  dynamicOptions: [{
    model: 'primary',
    schema: {
      const: true,
    },
    options: {
      fieldOptions: {
        class: ['btn-primary']
      }
    }
  }, {
    model: 'primary',
    schema: {
      not: {
        const: true,
      }
    },
    options: {
      fieldOptions: {
        class: ['btn-default']
      }
    }
  }]
}]
```

Read more about [dynamicOptions](https://jarvelov.gitbook.io/vue-form-json-schema/api/vue-form-json-schema/ui-schema/field/dynamic-options) in the documentation.
