### ISSUE TITLE
select / option not being selected from model

### ISSUE THREAD

**Issue by abh** [jarvelov/vue-form-json-schema#46]
First, thank you for vue-form-json-schema!

In my form I tried setting up a select input.  It's updating the model okay on updates, but it doesn't get initialized from the model on setup. What am I missing?

schema:

```
{
  "type": "object",
  "required": [
    "zone_name",
    "device_count",
  ],
  "properties": {
    "zone_name": {
      "type": "string"
    },
    "device_count": {
      "type": "string"
    },
    "contact_information": {
      "type": "string"
    }
  }
}
```

Relevant bits of UI schema:

[uischema.txt](https://github.com/jarvelov/vue-form-json-schema/files/4366878/uischema.txt)

And the javascript to setup the mini Vue app (the whole app is just this form...):

```
window.Vue.component('vendor-form', {
    name: 'vendor-form',
    template,
    data() {
        return {
            model: {
                zone_name: 'some_zone',
                device_count: "250000",
                contact_information: "hello, email us.",
            },
            state: { } ,
            valid: false,
            submitted: false,
            success: false,
            options: {
                castToSchemaType: true,
            },
            schema: schema,
            uiSchema: uiSchema
        };
    },
    methods: {
        onChangeState(value) {
            console.log("changestate: ", value);
            this.state = value;
        },
        onValidated(value) {
            console.log("validated: ", value);
            this.valid = value;
        },
        onSubmit(e) {
            e.preventDefault();

            this.submitted = true;
            this.options = {
              ...this.options,
              showValidationErrors: true,
            };

            if (this.valid) {

                console.log("POSTING!", this.model);

                axios.post('/manage/vendor/x', {
                    data: this.model,
                  })
                  .then(function (response) {
                    console.log(response);
                  })
                  .catch(function (error) {
                    console.log(error);
                  });

              this.success = true;
            }
        },
    },
});
```

Apologies if this is an obvious question; all this (Vue, etc) is new to me!

**Comment by jarvelov** [comment]
Hi,

Glad you like VFJS! Regarding your issue, can you post how you use the component in the template? I'm guessing you're using `v-model` since I'm not seeing any method to handle updates to the model so I just want to make sure you use `v-model="model"`.

**Comment by abh** [comment]
Yes,

```
    <form @submit="onSubmit">
    <vue-form-json-schema
      v-model="model"
      :schema="schema"
      :ui-schema="uiSchema"
      v-on:state-change="onChangeState"
      v-on:validated="onValidated"
    >
    </vue-form-json-schema>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">
                Save application
            </button>
        </div>
    </form>
```

**Comment by abh** [comment]
... and a related question; with "regular Vue" I can template out the select options, but with VFJS the only way I could figure out to do it was to spell it out in the ui schema, is that right?

**Comment by jarvelov** [comment]
All right, I've had a closer look at your code and see that the `selected` property was not set on the option with the corresponding value to the model. VFJS does not automatically set the option as selected as that has to be set in the field's `domProps`/`attrs` in the uiSchema.

To answer your previous question (and maybe even your next question): JavaScript to the rescue! You don't have to define field's manually, use JavaScript to generate your markup.

See here for a working example: https://codesandbox.io/s/example-1-g89d8

The option field's are generated by first creating an array of the options:

```js
  data() {
    return {
       // Array of the options' labels and values
      deviceCountOptions: [
        {
          label: "Up to 1,000 devices",
          value: "1000"
        },
        ...
        {
          label: "Up to 250,000 devices",
          value: "250000",
          selected: true, // We want to set which value will be preselected
        },
        ...
        {
          label: "More than five million devices",
          value: "5000001"
        }
      ]
    }
  }
```

Okay, so now we have an array of the options' labels and values, all we have to do now is to generate their `uiSchema`. The `uiSchema` does not have to be a `data` property, it can be a reactive computed property, that is a property of the `computed` property. This means we can dynamically generate the `uiSchema` using JavaScript

Okay, so now we loop over all the options and create the field's `uiSchema`

```js
  computed: {
    deviceCountOptionsUiSchema() {
      return this.deviceCountOptions.map(option => ({
        component: "option",
        fieldOptions: {
          domProps: {
            value: option.value,
            innerHTML: option.label,
            selected: option.selected,
          },
          attrs: {
            value: option.value,
          }
        }
      }));
    },
```

And then all we have to do is ensure that the `uiSchema` is also defined as a `computed` property add the result of the `this.deviceCountOptionsUiSchema` to it.

```js
  computed: {
    ...
    uiSchema() {
      return [
            ...
            {
              model: "device_count",
              component: "select",
              children: this.deviceCountOptionsUiSchema,
            }
            ...
      ]
    }
  }
```

Great, now we have a working, dynamically generated `uiSchema`! Hurray!

...yeah okay I hear you. "Dynamically generated? Looks somewhat static to me!"

And you're right, we might not have the luxury to get an array of the options where the option with the same value as the model is set as `selected`. However, don't fret! We can adjust our code just a tiny bit and achieve the same effect for situations when we don't know the model value in advance.

For simplicity's sake, let's assume we still have the array of options that we can loop over but instead of having a `selected` property already set on that array item with the corresponding value we can just check each item in the loop against the model:

```js
    deviceCountOptionsUiSchema() {
      return this.deviceCountOptions.map(option => ({
        component: "option",
        fieldOptions: {
          domProps: {
            value: option.value,
            innerHTML: option.label,
            selected: option.value === this.model.device_count, // Hey, look, we can just check the model value here and compare directly
          },
          attrs: {
            value: option.value,
          }
        }
      }));
    }
```

All right! Now we're talking! Powerful right? So why didn't we just do this directly? I'll tell you why: Performance.

Now when we use`this.model.device_count` in our code to render the `uiSchema`, Vue will very kindly remember that we used that value here and whenever `device_count` is updated, it will re-run this computed property. This causes a re-render whenever the user selects another option.

All right, but what's the harm in that, it works fine right? Well yeah, now it does, but as the form grows each added field in the `uiSchema` will have to re-render as well, and now that is bad for performance! VFJS does some additional checks to prevent unnecessary re-renders (as does Vue), but it can't catch everything and when you have 50+ fields in the `uiSchema` you will see that performance has degraded a lot.

All right, so what now, shouldn't I use `uiSchema` as a computed property then? The answer is, as with so many things: Maybe

For small forms with < 30 fields it should work just fine unless your field's components are very complex. When you need to generate the `uiSchema` dynamically with JavaScript this is the easiest method, so definitely try it out.

Okay, so when have over 30 fields it's goodbye performance then? Well no, there are many ways to achieve good performance, and the best way is to have the `uiSchema` as a static `data` property.

...okay, but that wouldn't work when you need to dynamically build the `uiSchema`, what am I to do? Well nothing prevents you from doing both!

There are several ways to keep your uiSchema "dynamic" without sacrificing performance. One of my favorite ways is to keep the uiSchema as a `data` property and generate it in the `created` lifecycle method. Like this:

```js
data() {
  return {
    uiSchema: []
  }
},
...
methods: {
  generateUiSchema() {
    // Return a dynamically generated uiSchema here!
  }
}
...
created() {
  this.uiSchema = this.generateUiSchema();
}
```

All right! Now that will generate the uiSchema once when the component is mounted, which allows for the uiSchema to be dynamically generated, but still not re-render the entire form every time the model updates, it is the best of both worlds!

I hope that this was helpful and that I answered your questions. If you have any more questions please feel free to ask them. If you need help with something specific try to recreate what you're having problems with in the CodeSandbox link above.

Cheers!

**Comment by abh** [comment]
Thank you, I really appreciate it! I'm trying to make it work and running into basic javascript problems. I'll see if I can get it working in the CodeSandbox.

**Comment by abh** [comment]
Alright, I got your example to work, thank you again!  I think adding a version of that as an example would be valuable.

I'm not sure yet how I get the "selected" attribute set correctly when the model is loaded from elsewhere, but I'll get to that later.

I tried changing the "type" to be a "number" instead of string, but then I always get a "must be a number" error. It does the same in the codesandbox: https://codesandbox.io/s/example-1-elzge  

Is that a select/options quirk or am I doing something wrong?

**Comment by jarvelov** [comment]
Regular HTML elements (i.e. <input>, <select> etc.) only emit values as strings and if you want them to be any other type you have to cast them as such. You probably want to use the `castToSchemaType` option as that casts the emitted value as the type specified in the JSON schema. 

```js
<vue-form-json-schema
  :options="options"

...

data () {
  return {
    options: {
      castToSchemaType: true
    }
  }
}
```

If you need more flexibility you can use a function to format the emitted value.

```js
data () {
  return {
    uiSchema: [{
      component: "select",
      fieldOptions: {
        on: {
          input: (event) => {
            // You can perform any synchronous action in here
            return Number(event.target.value);
          }
        }
      }
    }]
  }
}
```
