### ISSUE TITLE
problem with bootstrap-vue and b-form-checkbox field

### ISSUE THREAD

**Issue by marcogh** [jarvelov/vue-form-json-schema#52]
vue-form-json-schema with bootstrap-vue works very well except for the b-form-checkbox field.
The problems are:
* The checkbox iniitial status is always unchecked
* the checkbox state value doesn't react to the check/uncheck event, except the second click, when the value goes from true to false.
* Every other checkbox click doesn't change the checkbox state value

Maybe it's a bootstrap-vue bug...

[https://codesandbox.io/s/bootstrap-vue-checkbox-mqt07](https://codesandbox.io/s/bootstrap-vue-checkbox-mqt07)

**Comment by jarvelov** [comment]
Hi!

Thanks for reporting this. The problem is that the `b-form-checkbox` field is using a custom property for `v-model`. In [the documentation for bootstrap-vue](https://bootstrap-vue.org/docs/components/form-checkbox) we can see that that they use the `checked` property as the value for the v-model.

To make this work you have to use the `valueProp` field setting. You can see a working demo here: https://codesandbox.io/s/bootstrap-vue-checkbox-68hxd

The essential part is this:

```js
{
  component: "b-form-checkbox",
  model: "checkEnable",
  errorOptions: {
    class: ["is-invalid"]
  },
  valueProp: "checked", // This tells vue-form-json-schema to pass the field model to the 'checked' prop, instead of the default 'value' prop
  fieldOptions: {
    on: ["change"],
    props: {
      id: "input-1",
      name: "input-1"
    }
  }
}
```

**Comment by marcogh** [comment]
thank you very much, this solved the problem.
