### ISSUE TITLE
Problem with checkbox input field

### ISSUE THREAD

**Issue by p1fb** [jarvelov/vue-form-json-schema#66]
Hey there,

thank you for your great work! I've tested this plugin for an hour now and it seems like it will save my team and me a bunch of work.

Unfortunately, I have problems to make checkbox fields work like I would expect it. Maybe I am doing something wrong because regular Text fields work like a charm. Please have a look at my UI schema for the checkbox field:
```js
{
  component: 'input',
  model: 'isEnabled',
  fieldOptions: {
    class: ['form-control'],
    attrs: {
      type: 'checkbox',
    },
    on: 'click', // 'change' or 'input' does not fix my error
    domProps: {
      checked: true, // this works, the checkbox is checked by default
    },
  },
```
If I check the checkbox in the browser my VueJS debugger shows me that the model has an element `isEnabled` but the value is set to an empty string and does not change for subsequent clicks on the checkbox.

Thanks in advance
Fabian

**Comment by paolog22** [comment]
same problem here. schema default not working

**Comment by jarvelov** [comment]
Hi,

Native checkboxes have been a bit tricky to handle. I just released `v2.7.0` which makes it easier to work with checkboxes. Now you can use a checkbox like this:

```js
{
  component: 'input',
  model: 'isEnabled',
  valueProp: 'checked', // This sets the property which the field's model will be passed to
  eventProp: 'checked' // This sets which property is read from the event's target (event.target)
  fieldOptions: {
    on: ['click'], // When this event is triggered the 'valueProp' is read from the event's target element. i.e: event.target[valueProp]
    attrs: {
      type: 'checkbox',
    },
  },
},
```

This will render the equivalent of:

```vue
<input type="checkbox" :checked="model.isEnabled" @click="(event) => updateFieldModel(event.target.checked)" />
```

To get the input checked by default you will now as of `v2.7.0` only need to set the initial value in the `model`, like this:

```js
model: {
  isEnabled: true,
},
```

You can see a working demo of this here: https://codesandbox.io/s/example-1-usn90?file=/src/components/example-one.vue

@paolog22 I suspect your problem is not directly related to this issue given the issue you created earlier, #65. Check out my answer in that issue and see if it solves your problem.

**Comment by p1fb** [comment]
Hi @jarvelov ,

many thanks for your fast reply and your great work! I will try this today and come back to you then.

Cheers,
Fabian

**Comment by p1fb** [comment]
Hi @jarvelov ,

sorry for the late response.
It works like a charm! Thank you very much 👍 

Cheers,
Fabian
