### ISSUE TITLE
bootstrap-vue demo throws error about state

### ISSUE THREAD

**Issue by sdcuthbertson** [jarvelov/vue-form-json-schema#7]
Error is thrown in the console when using the `bootstrap-vue` example:

```
[Vue warn]: Invalid prop: type check failed for prop "state". Expected Boolean, String, got Object.

found in

---> <BFormInput>
       <VueFormJsonSchemaFieldWrapper>
         <VueFormJsonSchemaViewer>
           <DynamicJsonSchemaForm> at src/components/HtmlControls/DynamicJsonSchemaForm.vue
             <StatusOpenForFullPayment> at src/components/PageSections/StatusOpenForFullPayment.vue
               <PageStatusSections> at src/components/PageSections/PageStatusSections.vue
                 <PublicEventRegistration> at src/views/PublicEventRegistration.vue
                   <App> at src/App.vue
                     <Root>```

**Comment by jarvelov** [comment]
Thanks for notifying me.

`vue-form-json-schema` passes a number of props to the rendered components, however these are not documented as of yet.

In early development I lazily just named them to common words, like state, which were bound to cause conflicts. Looking at the documentation for `bootstrap-vue` I can see [they have a prop for the `<b-form-input>` called state](https://bootstrap-vue.js.org/docs/components/form-input#component-reference), which now receives the state prop from `vue-form-json-schema`, and causes this error.

All props now have a prefixed version, for example `state` -> `vfjsState`. I've omitted mentioning these props in the documentation since I wasn't sure about their format and names, however I think they have been quite stable for a while now.

I will release a new major version where I drop the common named props and just keep the `vfjs` prefixed ones. I'll also include some information in the documentation and an example showing how to use these props in this release.

**Comment by epicfaace** [comment]
@jarvelov I'm wondering why you decided to prefix these props? Couldn't you have just made sure people wrapped their components in a `<div>` or something?

I'm wondering because I'm thinking whether this is also the way to go with mozilla-services/react-jsonschema-form.

**Comment by jarvelov** [comment]
> @jarvelov I'm wondering why you decided to prefix these props? Couldn't you have just made sure people wrapped their components in a `<div>` or something?
> 
> I'm wondering because I'm thinking whether this is also the way to go with mozilla-services/react-jsonschema-form. https://github.com/mozilla-services/react-jsonschema-form

The reasoning behind this decision was for the wrapped component to be able to make use of the props passed to each component, I haven't figured out all ways to use vue-form-json-schema yet and wouldn't want to limit any ways to use it simply because I can't see the use case for some implementation. It might be really useful to have the form state accessible in the component. If however if we passed that prop to the component as `state` rather than `vfjsState` then we limit the ways you can use this package with the components you already have.

Also, this project was developed so the developer didn't have to change the markup. Having to wrap each component in a div would be at best a nuisance and at worst break functionality and css styles.

Regarding react-jsonschema-form I would have to say that even though there are many similarities between it and this project there are some important differences. It served in some ways as inspiration for this project, however I would direct that question to their issue tracker as I'm not capable of giving recommendations for that project.
