### ISSUE TITLE
md-switch not rendering nor functioning correctly

### ISSUE THREAD

**Issue by DavidBord** [jarvelov/vue-form-json-schema#89]
Hi,
I hope all is well.
First, I would like to say that this is a great library!
I am using vuematerial as framework and I am trying to render md-switch.
I have no luck in either using its functionality nor displaying its label.
Trying naively with
`{component: 'md-switch', fieldOptions: {domProps: {innerHTML: 'bool-label'}}, model: 'bool'}`
I also tried replacing innerHTML with scopedSlots as I saw in another issue here.
I would appreciate your help here.

**Comment by jarvelov** [comment]
Hi David,

Glad you like it! I think the best solution would be to use another element for the label and put it as the child of the `md-switch` component, like this:

```js
{
  component: "md-switch",
  model: "bool",
  children: [
    {
      component: "span",
      fieldOptions: {
        domProps: {
          innerHTML: "bool-label",
        },
      },
    },
  ],
},
```

Regarding the functionality, it takes a couple of things to make it work. Unfortunately the [md-switch component](https://vuematerial.io/components/switch) emits either the prop value or null when clicked, depending on whether it is checked or not. Because of this we have to use some javascript to set the correct value to return to VFJS in the `change` event handler.

```js
fieldOptions: {
  props: {
    value: true, // Here we set the static value of the switch which it has when it is enabled
  },
  on: {
    change: (value) => {
      return !value; // Here we ensure we return the correct value to VFJS, i.e. true becomes false and null becomes true
    },
  },
},
```

Here's a working demo using the `md-switch` component: https://codesandbox.io/s/example-1-forked-rk9nl

However, your needs might stretch beyond a basic `true`/`false` scenario. Say for example that you might need to have a dynamic value for `md-switch`, i.e. when it is enabled you want the value to be `candy` and when it is disabled you want the value to be `spinach`.

This can be solved by either moving the `uiSchema` to be a `computed` property or by using `dynamicOptions`. Lets first look at how to solve this using a `computed` property.

```js
computed: {
  uiSchema() {
    return [
      {
        component: "md-switch",
        model: "bool",
        fieldOptions: {
          props: {
            // Here we use the same logic as in the change handler below to set the component's value
            value: !this.model.bool
          },
          on: {
            change: value => {
              return !value; // Here we ensure we return the correct value to VFJS, i.e. true becomes false and null becomes true
            }
          }
        },
        children: [
          {
            component: "span",
            fieldOptions: {
              domProps: {
                innerHTML: "bool-label"
              }
            }
          }
        ]
      }
    ];
  }
}

```

And now with `dynamicOptions`.

```js
{
  component: "md-switch",
  model: "food",
  fieldOptions: {
    on: {
      change: (value) => {
        return !value; // Here we ensure we return the correct value to VFJS, i.e. true becomes false and null becomes true
      },
    },
  },
  dynamicOptions: [
    {
      model: "food",
      schema: {
        type: "string",
        const: "spinach",
      },
      options: {
        fieldOptions: {
          props: {
            value: "candy",
          },
        },
      },
    },
    {
      model: "food",
      schema: {
        type: "string",
        const: "candy",
      },
      options: {
        fieldOptions: {
          props: {
            value: "spinach",
          },
        },
      },
    },
  ],
  children: [
    {
      component: "span",
      fieldOptions: {
        domProps: {
          innerHTML: "bool-label",
        },
      },
    },
  ],
},
```

The benefits of using `dynamicOptions` is that this method does not require the `uiSchema` to be a `computed` property, which improves performance. The obvious disadvantage is that it requires a lot more configuration.

Hope this help solve the problem you had. Let me know if this doesn't solve your problems or if you run into any other!

**Comment by DavidBord** [comment]
It is working, thank you
